version: 2
updates:  
  - package-ecosystem: "npm"
    directory: "/officegen-api"
    schedule:
      interval: "weekly"
      day: "saturday"
    reviewers:
      - "HlexNC"

  - package-ecosystem: "pip"
    directory: "/python-api"
    schedule:
      interval: "weekly"
      day: "saturday"
    reviewers:
      - "HlexNC"

  - package-ecosystem: "npm"
    directory: "/document-conversion"
    schedule:
      interval: "weekly"
      day: "saturday"
    reviewers:
      - "HlexNC"
# Interval can be 'live', 'daily', 'weekly', or 'monthly'
